#include "Dialect/Frisk/IR/FriskDialect.h"
#include "Dialect/Frisk/IR/FriskOps.h"
#include "Dialect/Frisk/Transforms/Passes.h"
#include "gtest/gtest.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/PassManager.h"
#include <cmath>
#include <limits>
#include <optional>
#include <vector>

using namespace mlir;
using namespace mlir::frisk;
namespace {
// CPU mathematical reference, independent of layout selection/lowering. These
// exact f32 inputs test import semantics, not GPU reassociation equivalence.
float combine(StringRef kind, float a, float b) {
  if (kind == "sum" || kind == "add") return a + b;
  if (std::isnan(a) || std::isnan(b))
    return std::numeric_limits<float>::quiet_NaN();
  if (a == 0.0f && b == 0.0f) {
    bool negative = kind == "max" ? std::signbit(a) && std::signbit(b)
                                  : std::signbit(a) || std::signbit(b);
    return negative ? -0.0f : 0.0f;
  }
  return kind == "max" ? std::max(a,b) : std::min(a,b);
}

// Interpret only the small pure SSA vocabulary generated by this test. An
// unexpected op is a failure, rather than silently replaced by its input.
std::optional<std::vector<float>> evaluate(Value value) {
  auto *op = value.getDefiningOp();
  if (!op) return std::nullopt;
  if (auto constant = dyn_cast<arith::ConstantOp>(op)) {
    auto dense = dyn_cast<DenseFPElementsAttr>(constant.getValue());
    if (!dense) return std::nullopt;
    std::vector<float> result;
    for (APFloat x : dense.getValues<APFloat>()) result.push_back(x.convertToFloat());
    return result;
  }
  if (auto reduce = dyn_cast<ReduceTensorOp>(op)) {
    auto source = evaluate(reduce.getSource());
    auto type = cast<RankedTensorType>(reduce.getSource().getType());
    if (!source || type.getRank() != 2 || reduce.getDim() != 1) return std::nullopt;
    std::vector<float> result;
    for (int64_t row = 0; row < type.getDimSize(0); ++row) {
      // Pairwise tree, unlike the legacy reference's sequential fold below.
      std::vector<float> level(source->begin() + row * type.getDimSize(1),
                               source->begin() + (row + 1) * type.getDimSize(1));
      while (level.size() > 1) {
        std::vector<float> next;
        for (unsigned i = 0; i < level.size(); i += 2)
          next.push_back(combine(reduce.getKind(), level[i], level[i+1]));
        level = std::move(next);
      }
      result.push_back(level.front());
    }
    return result;
  }
  StringRef kind;
  if (isa<arith::AddFOp>(op)) kind = "sum";
  else if (isa<arith::MaximumFOp>(op)) kind = "max";
  else if (isa<arith::MinimumFOp>(op)) kind = "min";
  else return std::nullopt;
  auto lhs = evaluate(op->getOperand(0)), rhs = evaluate(op->getOperand(1));
  if (!lhs || !rhs || lhs->size() != rhs->size()) return std::nullopt;
  for (unsigned i = 0; i < lhs->size(); ++i) (*lhs)[i] = combine(kind, (*lhs)[i], (*rhs)[i]);
  return lhs;
}

TEST(LegacyNormalizationNumericTest, ClearAndMergeMatchExplicitCPUContract) {
  MLIRContext context;
  context.loadDialect<FriskDialect, arith::ArithDialect, func::FuncDialect,
                      memref::MemRefDialect>();
  float nan = std::numeric_limits<float>::quiet_NaN();
  for (StringRef kind : {"add", "max", "min"})
    for (bool clear : {false, true})
      for (auto [input, old] : {std::pair<float,float>{2.0f,5.0f},
                               {-0.0f,-0.0f}, {0.0f,-0.0f}, {nan,1.0f}, {1.0f,nan}}) {
        SCOPED_TRACE(kind.str() + (clear ? " clear" : " merge"));
        auto module = parseSourceString<ModuleOp>(R"mlir(
module attributes {frisk.legacy_semantics="tensor_v1"} {
  func.func @f(%out:memref<4xf32,1>) { return }
})mlir", &context);
        ASSERT_TRUE(module);
        auto fn = *module->getOps<func::FuncOp>().begin();
        OpBuilder b(fn.getBody().front().getTerminator());
        auto loc = fn.getLoc();
        auto src = b.create<memref::AllocOp>(loc, MemRefType::get({4,4}, b.getF32Type()));
        auto dst = b.create<memref::AllocOp>(loc, MemRefType::get({4}, b.getF32Type()));
        b.create<FillOp>(loc, src, b.getF32FloatAttr(input));
        b.create<FillOp>(loc, dst, b.getF32FloatAttr(old));
        b.create<ReduceOp>(loc, src, dst, kind, int64_t{1}, clear);
        b.create<CopyOp>(loc, dst, fn.getArgument(0), ValueRange{}, ValueRange{});
        PassManager pm(&context);
        pm.addPass(createNormalizeLayoutIRPass());
        ASSERT_TRUE(succeeded(pm.run(*module)));
        TileStoreOp store;
        module->walk([&](TileStoreOp op) { store = op; });
        ASSERT_TRUE(store);
        auto actual = evaluate(store.getValue());
        ASSERT_TRUE(actual);
        ASSERT_EQ(actual->size(), 4u);
        float expected = input;
        for (unsigned i = 1; i < 4; ++i) expected = combine(kind, expected, input);
        if (!clear) expected = combine(kind, old, expected);
        for (float result : *actual) {
          if (std::isnan(expected)) EXPECT_TRUE(std::isnan(result));
          else {
            EXPECT_EQ(result, expected);
            if (expected == 0.0f) EXPECT_EQ(std::signbit(result), std::signbit(expected));
          }
        }
      }
}
} // namespace
